"""add entries.audio_file_path and ai_results.acoustic_features

Revision ID: 4674989821f7
Revises: 3973a8111b8e
Create Date: 2026-08-25 22:13:54.165261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4674989821f7'
down_revision: Union[str, None] = '3973a8111b8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_results', sa.Column('acoustic_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('entries', sa.Column('audio_file_path', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entries', 'audio_file_path')
    op.drop_column('ai_results', 'acoustic_features')
    # ### end Alembic commands ###
