"""add entries.systolic_bp, entries.diastolic_bp, entries.blood_sugar_mg_dl

Revision ID: 95fc7e1824e7
Revises: 4674989821f7
Create Date: 2026-09-07 11:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95fc7e1824e7'
down_revision: Union[str, None] = '4674989821f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('systolic_bp', sa.Integer(), nullable=True))
    op.add_column('entries', sa.Column('diastolic_bp', sa.Integer(), nullable=True))
    op.add_column('entries', sa.Column('blood_sugar_mg_dl', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entries', 'blood_sugar_mg_dl')
    op.drop_column('entries', 'diastolic_bp')
    op.drop_column('entries', 'systolic_bp')
    # ### end Alembic commands ###
